# примеры API-запросов

@baseUrl = http://localhost:8000/api
@ADMIN1 = paste your token here
@ADMIN2 = paste your token here
@SIMPLE_USER = paste your token here


# получение объявлений
GET {{baseUrl}}/advertisements/69
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{ADMIN1}}

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/69/
Content-Type: application/json
Authorization: Token {{ADMIN2}}

{
  "status": "DRAFT"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2020-10-01
Content-Type: application/json

###

# удаление обьявления
DELETE {{baseUrl}}/advertisements/77/
Authorization: Token {{ADMIN1}}

###

# добавление обьявления в избранные
PATCH {{baseUrl}}/advertisements/45/add_favourite/
Authorization: Token {{SIMPLE_USER}}
Content-Type: application/json

###

# получение избранных обьявлений для текущего пользователя
GET {{baseUrl}}/advertisements/get_favourites/
Authorization: Token {{SIMPLE_USER}}

###

# создание черновика
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{ADMIN1}}

{
  "title": "Шкаф IKEA",
  "description": "Срочно",
  "status": "DRAFT"
}

###

# Получение черновиков
GET {{baseUrl}}/advertisements/?status=DRAFT
Content-Type: application/json
Authorization: Token {{ADMIN1}}