# Generated by Django 4.0.4 on 2022-04-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articlescope_scope_articles_articlescope_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ['-is_main'], 'verbose_name': 'Тематики статьи', 'verbose_name_plural': 'Тематики статей'},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tag',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='articlescope',
            name='scope',
        ),
        migrations.AddField(
            model_name='articlescope',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.scope', verbose_name='Раздел'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='articles',
            field=models.ManyToManyField(through='articles.ArticleScope', to='articles.article'),
        ),
    ]
