# Generated by Django 4.0.4 on 2022-04-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
    ]
